### ISSUE TITLE
JupyterLab 4 PyPi release

### ISSUE THREAD

**Issue by kevinjohncutler** [jupyterlab-contrib/jupyterlab-favorites#17]
I saw the pull request got merged a while back, is the extension ready for a pypi release? I have not been able to get a local install to complete.

**Comment by krassowski** [comment]
It looks like the releaser is setup, I will try to carry out a 4.0 release.

**Comment by fcollonval** [comment]
> I did not release the package yet because there is an error with the icon next to the breadcrumb that is badly positioned and not accessible for click; see skipped integration test: https://github.com/jupyterlab-contrib/jupyterlab-favorites/blob/a07b08c2cadeccdac6947fa0416afdb0c82c4927/ui-tests/tests/jupyterlab_favorites.spec.ts#L48

**Comment by kevinjohncutler** [comment]
How badly does this affect functionality? It might be worth releasing a version with that bug if folder names still appear at the top and are clickable.

**Comment by fcollonval** [comment]
Version 3.2.0 has been released with support for Lab 4: https://pypi.org/project/jupyterlab-favorites/

**Comment by kevinjohncutler** [comment]
Huge thanks @fcollonval, such an improvement to my workflow (and sanity) to have this back!
